import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import TextBox from "@/components/TextBox";
import Block from "@/components/Block";
import ApiControls from "@/components/ApiControls";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Block>
            <TextBox text="First Card - Welcome to our application!" />
            <TextBox text="Second Card - Explore the features and functionality." />
            <TextBox text="Third Card - Get started with your journey today." />
          </Block>

          <Block>
            <TextBox text="dupa" />
            <TextBox text="dupa" />
            <TextBox text="dupa" />
          </Block>

          <Block>
            <ApiControls />
          </Block>
        </main>
      </div>
    </>
  );
}
