import enum
from typing import Annotated

from pydantic import BaseModel, Field


class AgentRole(str, enum.Enum):
    """Agent role."""
    EXECUTOR = "EXECUTOR"
    """The agent that is executing the original request."""
    SUPERVISOR = "SUPERVISOR"
    """The agent that oversees the executor."""


class Message(BaseModel):
    """Message generated by the LLM agent."""
    role: AgentRole
    content: Annotated[str, Field(min_length=1)]
